Суворов Никита
VictoriaOtm/units-autumn-2021 pull request #10
Opened 2021-09-30 18:40 UTC by Tullerpeton

2021-10-01 10:43 UTC, lev4rT requested changes

2021-10-01 10:43 UTC, lev4rT commented on src/Order/Order.test.tsx
> +	});
Использование `it.each()` абсолютно оправдано, но синтаксис с деструктуризацией объекта лично мне довольно непросто читать.

Предлагаю заменить следующие строчки на что-то вроде
```
it.each([
		{date: 0},
		{shop: ''},
		{}
	])('test render with null', (data) => {
		const wrapper = shallow(<OrderComponent order={data}/>);
		expect(wrapper.getElement()).toBeNull();
	});
```

2021-10-01 10:43 UTC, lev4rT commented on src/Order/Order.test.tsx
> +		expect(wrapper).toMatchSnapshot();
Опять же предлагаю избавиться от синтаксиса с деструктуризацией

2021-10-01 10:43 UTC, lev4rT commented on src/utils/sortOrders.test.ts
> +	});
Одинаковое название у тестов, из которого не совсем понятно что тестируется. Лучше как-то переименовать один из них

2021-10-01 10:43 UTC, lev4rT commented on src/utils/sortOrders.test.ts
> +		expect(result).toBe(sortByDate);
Можно избавиться от введения лишней переменной `result`, повысив удобочитаемость:
```
expect(getSortFunction(sortTypes.DATE)).toBe(sortByDate);
```

Предлагаю сделать так и в других случаях

2021-10-01 10:43 UTC, lev4rT commented on src/utils/sortOrders.ts
> +	// }
![image](https://user-images.githubusercontent.com/64415914/135606992-779a036b-b125-4839-84c2-705b69fce40d.png)

2021-10-01 10:43 UTC, lev4rT commented on tsconfig.json
> +    "jsx": "react-jsx",
Не понял откуда вылезло, у меня таких изменений нет

2021-10-01 12:40 UTC, Tullerpeton commented on src/utils/sortOrders.ts
> +	// }
Извините пожалуйста

2021-10-01 12:47 UTC, lev4rT approved these changes

2021-10-01 12:53 UTC, DuckLuckBreakout approved these changes
Похоже Денис все отловил

2021-10-02 11:38 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +		expect(result).toBe(0);
что-то тут не то, как у тебя прошли эти тесты? там же должно быть -1 и 1, точно данные верно передал?

2021-10-02 11:45 UTC, Tullerpeton commented on src/utils/sortOrders.test.ts
> +		expect(result).toBe(0);
не ту функцию вызывал
изменил `sortByItemCount` -> `sortDate`

2021-10-17 09:08 UTC, closed without merging