Коваленко Иван.
VictoriaOtm/units-autumn-2021 pull request #14
Opened 2021-09-30 18:53 UTC by DuckLuckBreakout

2021-10-01 11:01 UTC, lev4rT requested changes

2021-10-01 11:01 UTC, lev4rT commented on src/Order/Order.test.tsx
> +		getDate.mockReturnValue('date');
Не знаю как у тебя, но у меня писало ошибку в IDE если написать прямо так. Помогло следующее:
```
(getDate as jest.Mock).mockReturnValue('some string');
```

2021-10-01 11:01 UTC, lev4rT commented on src/Order/Order.test.tsx
> +	});
Сам тест на то, что возвращается `null` понятен, но не совсем понятны входные данные. У типа `Order` вообще нет поля `data`, есть только `date` (lol). Также не хватает проверки на то, что передаваемого объекта нет поля `date`

Т.к. обе эти проверки возвращают `null` - предлагаю использовать `it.each()`

Синтаксис с деструктуризацией предлагаю заменить на более удобочитаемый, чтобы в конечно итоге получилась строка примерно следующего вида: `const wrapper = shallow(<OrderComponent order={data}/>);`

2021-10-01 11:01 UTC, lev4rT commented on src/utils/sortOrders.test.ts
> +		order2.items = [];
Предлагаю управиться с созданием необходимого объекта в одну строку:
```
const order1 = { items: [] };
```

Аналогично для order2 и везде, где встречается подобное

И если мне не изменяет память, то сами тесты мы можем писать на чисто JS

2021-10-01 11:01 UTC, lev4rT commented on src/utils/sortOrders.test.ts
> +		expect(result).toEqual(0);
Можно избавиться от введения лишней переменной `result`, повысив удобочитаемость:
```
expect(sortByItemCount(order1, order2)).toEqual(0);
```
Предлагаю сделать так и в других случаях

2021-10-01 11:01 UTC, lev4rT commented on src/utils/sortOrders.test.ts
> +	])('test empty order date №%#', (data) => {
не понял что за символы в названии теста

2021-10-01 11:01 UTC, lev4rT commented on src/utils/sortOrders.ts
> +	// }
![image](https://user-images.githubusercontent.com/64415914/135606992-779a036b-b125-4839-84c2-705b69fce40d.png)

2021-10-01 11:31 UTC, lev4rT approved these changes

2021-10-01 12:04 UTC, Tullerpeton requested changes

2021-10-01 12:04 UTC, Tullerpeton commented on src/utils/sortOrders.test.ts
> +		const order2: Order = {date: 2};
Fix code-style

2021-10-01 12:04 UTC, Tullerpeton commented on src/utils/sortOrders.test.ts
> +	});
Duplicate tests

2021-10-01 12:04 UTC, Tullerpeton commented on src/utils/sortOrders.test.ts
> +	});
rename test-case

2021-10-01 12:14 UTC, Tullerpeton approved these changes

2021-10-02 11:48 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +import {sortByDate, sortByItemCount } from './sortOrders';
не вижу тестов на sortOrders и getSortFunction

2021-10-06 14:28 UTC, DuckLuckBreakout commented on src/utils/sortOrders.test.ts
> +import {sortByDate, sortByItemCount } from './sortOrders';
Добавил тесты для `getSortFunction` и  `sortOrders`

2021-10-17 09:10 UTC, closed without merging