Егоров Алексей
VictoriaOtm/units-autumn-2021 pull request #20
Opened 2021-10-01 10:21 UTC by pekanboy

2021-10-01 12:47 UTC, SergTyapkin requested changes

2021-10-01 12:47 UTC, SergTyapkin commented on src/Order/Order.test.tsx
> +		expect(wrapper.getElement()).toBeNull();
Тут ещё можно проверить на то, что `getDate()` не будет вызвана. Ведь если переданного объекта нет полей `shop` или `date`, то в самом начале будет вызван `return`.
А снапшот на этот случай, наверняка, создаётся пустой, так что лучше, всё-таки проверить не вызов функции

2021-10-01 12:47 UTC, SergTyapkin commented on src/Order/Order.test.tsx
> +		};
Вместо того, чтобы руками писать order'ы, лучше сделать test.each(fakeOrders), и импортнуть их из файла. Они ведь для этого и созданы.

2021-10-01 12:47 UTC, SergTyapkin commented on src/Order/Order.test.tsx
> +		expect(wrapper.getElement()).toBeNull();
Снапшот даже вообще не создаётся на этот случай. Посмотри в `Order.test.tsx.snap`

2021-10-01 12:47 UTC, SergTyapkin commented on src/utils/sortOrders.test.ts
> +});
А почему не объединить эти две проверки в одну, и везде в массивах указывать значение `expected` ?

2021-10-01 12:47 UTC, SergTyapkin commented on src/utils/sortOrders.test.ts
> +});
Эти две тоже в одну тогда

2021-10-01 12:47 UTC, SergTyapkin commented on src/utils/sortOrders.test.ts
> +describe('sortOrders function', () => {
Не хватает проверок на вызов и не вызов самой передаваемой функции. 
Для этого есть `jest.fun()`, у которой и можно проверять её вызванность.

2021-10-01 12:47 UTC, SergTyapkin commented on src/utils/sortOrders.ts
> -
А исходники то зачем кастрировать?
Это, хоть, и TypeScript, так что в IDE тебе подсветит, что ты не можешь передать пустой агрумент. 
Тем не менее, передать туда `undefined` возможно, и можно на это сделать тест.

А удалять строки с return'ами, потому что они портят итоговое покрытие - это уже последнее дело)

2021-10-01 12:51 UTC, pekanboy commented on src/Order/Order.test.tsx
> +		};
Я подумал, что фейковые ордеры могут извне изменить, что повлияет на тесты. Они ведь были созданы чтобы просто "что-то" отрисовать для визуализации, но не для того, чтобы их использовать в тестах. Мжно отдельный

2021-10-01 12:54 UTC, pekanboy commented on src/utils/sortOrders.test.ts
> +});
Можно и так, но это сделано для визуализации, чтобы отделить область проверок. Мне по крайней мере так понятнее читать код

2021-10-01 12:54 UTC, pekanboy commented on src/utils/sortOrders.test.ts
> +});
Аналогично

2021-10-01 12:55 UTC, pekanboy commented on src/utils/sortOrders.ts
> -
На лекции сказали, что можно удалить, ничего не знаю))))

2021-10-01 12:56 UTC, pekanboy commented on src/utils/sortOrders.ts
> -
Эта проверка всё равно в любом случае излишняя

2021-10-01 13:05 UTC, pekanboy commented on src/Order/Order.test.tsx
> +		expect(wrapper.getElement()).toBeNull();
Снапшот не создаётся, потому что ничего не отрисовывается после этого теста.

2021-10-01 13:06 UTC, pekanboy commented on src/Order/Order.test.tsx
> +		expect(wrapper.getElement()).toBeNull();
Можно добавить проверку на вызов функции getDate, но я считаю это будет антипаттерном, потому что мы будет делать 2 проверки в тесте

2021-10-01 13:08 UTC, pekanboy commented on src/Order/Order.test.tsx
> +		expect(wrapper.getElement()).toBeNull();
сделал отдельный тест для этого

2021-10-01 13:19 UTC, pekanboy commented on src/utils/sortOrders.test.ts
> +describe('sortOrders function', () => {
комплит

2021-10-01 13:21 UTC, SergTyapkin commented on src/Order/Order.test.tsx
> +		expect(wrapper.getElement()).toBeNull();
> Снапшот не создаётся, потому что ничего не отрисовывается после этого теста.

Так в том то и дело, что нам не надо тестить пустые снапшоты...

2021-10-01 13:22 UTC, SergTyapkin commented on src/Order/Order.test.tsx
> +		};
Ну можешь написать перед этим
```JS
const myTestOrders = Object.assign(fakeOrders);
```
И кидать в тесты myTestOrders, не боясь за fakeOrders

2021-10-01 13:23 UTC, SergTyapkin commented on src/utils/sortOrders.ts
> -
> На лекции сказали, что можно удалить, ничего не знаю))))

О как. Не знал. Ну тогда не посморишь

2021-10-01 13:28 UTC, SergTyapkin approved these changes

2021-10-01 13:28 UTC, SergTyapkin approved these changes

2021-10-02 13:39 UTC, VictoriaOtm commented on src/Order/Order.test.tsx
> +		jest.clearAllMocks();
в afterAll здесь правильнее использовать resetModules, подробнее: https://stackoverflow.com/questions/58151010/difference-between-resetallmocks-resetmodules-resetmoduleregistry-restoreallm

2021-10-02 13:42 UTC, VictoriaOtm commented on src/Order/Order.test.tsx
> +		expect(getDate).toBeCalledTimes(1);
вообще можно было бы объединить здесь (и ниже там, где снапшот не пустой) снапшот и проверку вызова, этот тот самый случай, когда ты не нарушаешь атомарность, потому что снапшот и вызов метода неразрывно связаны. Тогда лишние тесты не придется писать, раздувать их количество зря тоже не стоит

2021-10-02 13:45 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +		expect(sortFunction.mock.calls.length).toBe(1);
а можно просто expect(sortFunction).toHaveBeenCalledTimes(1)

2021-10-02 22:25 UTC, pekanboy commented on src/Order/Order.test.tsx
> +		jest.clearAllMocks();
complete

2021-10-02 22:26 UTC, pekanboy commented on src/Order/Order.test.tsx
> +		expect(getDate).toBeCalledTimes(1);
complete

2021-10-02 22:27 UTC, pekanboy commented on src/utils/sortOrders.test.ts
> +		expect(sortFunction.mock.calls.length).toBe(1);
complete

2021-10-17 11:41 UTC, closed without merging